language: node_js
node_js: "10"

addons:
  apt:
    packages:
        - google-chrome-stable

script:
    - git checkout -b travis-save-branch
    - git fetch origin develop:develop
    - npm run test
    - npm run build
